name: ArenaOneShot
main: mc.alk.oitc.OneShot
version: 1.1
depend: [BattleArena]
author: alkarinv
authors: [adambor]
description: Version 1.1 of oneshot
commands:
    os:
        aliases: [oneshot]
        usage: /os setItem <item name>